### PR TITLE
Enable multi-node subscriptions.

### LINKED ISSUE #2: Consumers from another node in the cluster are not registered.
I'm seeing that consumers that exist on another node in the Erlang cluster are not being registered as consumers. I've verified that the consumer 
```elixir
iex(passportqa@192.168.81.6)3> [{pid, producer}] = Registry.lookup(Registry.Subscriptions, :producers)            
[{#PID<0.1073.0>, MyApp.Producer}]                       
iex(passportqa@192.168.81.6)4> UmbrellaStage.Checker.check_producer_subscribers(pid, producer)                    
[]                          
iex(passportqa@192.168.81.6)5> Registry.lookup(Registry.Subscriptions, :consumers)                                
[]                      
iex(passportqa@192.168.81.6)6> Node.list()               
[:"myapp@192.168.125.9",]    # this is the consumer
```

In case it's useful information, I'm using peerage to cluster pods in kubernetes.

### PR DESCRIPTION
**Pull request by athal7**
Resolves #2

This uses mnesia instead of Registry, since it is replicated across all
of the nodes in a cluster.

### CODE REVIEW

**Comment by iacobson** [comment]
Thanks so much for contributing, really appreciate it! 

I was investigating your issue yesterday and indeed, the Registry cannot handle multi node. So the mnesia sounds like a very good solution. I will have some time tomorrow to test it, and try to understand a bit more about distributed systems.

Can you please tell me what would be the use case? Do you try to deploy a producer on one node and a consumer on another? or you deploy the full umbrella apps on 2 nodes, and then try to connect between them? (eg. if the producer dies on one node, it will be replaced by another producer on another node?)

**Comment by athal7** [comment]
My pleasure, thanks for being so responsive!

You got it, the use case is a producer on one node and a consumer on another node. Given that this is within Kubernetes, if the producer dies it should get replaced in short order.

One other thing I noticed here is that only one producer gets subscribed to from each consumer, so if I add replicas to the producer node, it seems I may need to do something like https://github.com/princemaple/dist_stages to ensure all consumer subscriptions go to a single globally registered producer.

**Comment by athal7** [comment]
I'm working on testing this branch out with the rest of my code to see if it solves the issue. I'll report back on how that goes.

**Comment by athal7** [comment]
hmm, still no dice yet. This is from the producer node:
```elixir
iex(myapp@192.168.89.7)1> UmbrellaStage.Registration.find(:consumers)                               
[]                        
iex(myapp@192.168.89.7)2> UmbrellaStage.Registration.find(:producers)                               
[{MyApp.Producer, #PID<0.1118.0>}]     
```

**Comment by iacobson** [comment]
I will try to look into it today as well. Do you think this could help us?
https://github.com/bitwalker/swarm

Please note that one advantage of using Registry in single node app was that when a registered process died, would be removed from the registry. When the process would be restarted by the supervision tree, would get re-registered, and could subcribe/be subscribed again.

So we need to consider this aspect as well.

**Comment by athal7** [comment]
Ah yes swarm may fit the needs better because of that feature. Good thinking.

**Comment by iacobson** [comment]
I still do not get how such a distributed system would work. So we do not speak about a failover/takeover, where we run the full app on more notes that would ensure fault tolerance.

Our case is different. We want just part of an umbrella app (which happen to be a GenStage consumer) to run on a different node, and communicate with the rest of the umbrella on another node. Doesn't that mean that we actually speak about 2 different apps ? (Jose Valim response here: https://groups.google.com/forum/#!topic/elixir-lang-core/X4pquETZKWQ)

So before thinking about automatic subscriptions, I'm not sure about the architecture itself. How I could do it manually, before thinking about automation.

What I'm trying to do. I modified a bit the demo application I used for the umbrella_stage blog posts. On the branch `distributed` https://github.com/iacobson/blog_stockr/tree/distributed I have a single node working version of multiple gen stages inside an umbrella.
You can start it with `iex -S mix` then call `Shared.DataGenerator.generate()` and there is random data going in the system through the gen_stages.
I try to begin from there, and start somehow one of the consumers on a different node, then manually subscribe it to the producer on the "main" node. 

Does this make any sense?

**Comment by iacobson** [comment]
Followup to the post above:
- I created a new branch of the app (https://github.com/iacobson/blog_stockr/tree/distributed-manual), where I removed one of the consumers from the supervision tree. So `MyUkApp.ReceiveConsumer` does not start automatically when we start the umbrella app
- I create an `umbrella` node and start the app: `iex --sname umbrella  -S mix`
- I create another node called `consumer` : `iex --sname consumer`
- on the main umbrella node I call the random data generator: `iex(umbrella@mbp)1> Shared.DataGenerator.generate()`
- of course, nothing happens, as the consumer is not up
- on the consumer node I start the consumer, by `:rpc` calling it from the umbrella node `iex(consumer@mbp)1> :rpc.call(:"umbrella@mbp", MyUkApp.ReceiveConsumer, :start_link, [[]])`
- I immediately start to **receive data in the consumer node**. Eg:
```
[UK interface] : %{company: "company: US: A", currency: :gbp, price_per_share: 65}
[UK interface] : %{company: "company: US: B", currency: :gbp, price_per_share: 495}
[UK interface] : %{company: "company: GER: E", currency: :gbp, price_per_share: 560}
[UK interface] : %{company: "company: GER: A", currency: :gbp, price_per_share: 722}
```

So this scenario works with the default Registry implementation of the `umbrella_stage`.
This however assumes that there is some kind of master/main node, and the other nodes know how to start the required nodes from the main one ...
Don't know if it's ideal.

**Comment by athal7** [comment]
Wow, this is an awesome level of detail and research @iacobson. I think the insight that this is one applications and not two is very helpful for me, and I think it probably makes the most sense to go back to that, and use genstage within each node across the umbrella, rather than trying to treat it in the way that's deemed incorrect.

With that immediate use case solved, is this type of feature something you'll want to support in umbrella_stage? It does sound like something useful, but from your research also sounds like a lot of work and already doable / arguably out of the scope of what this project is trying to achieve. I don't mind closing this pull request and related issue if that's the case.

Either way, thank you for the collective deep dive.

**Comment by iacobson** [comment]
While the topic is very interesting, I do not see (at least) yet a way to handle the distributed systems. As you saw in the example above, if you distribute some servers from the main app, the initial solution works.

But there are so many ways to do the distribution, and not sure if one solution would fit all of them.

So unless you have some idea, maybe we can close the PR. On the other hand, if you have any suggestion, or different approach then the one I used in the  comment above, we can use that example branch to work together.

Just for my curiosity, when you say **"use genstage within each node across the umbrella"**, how do you do that? How do you actually start the umbrella on multiple nodes? Is it each app in the umbrella on different node? if yes, would that still be an umbrella?

Thanks again for investigating this subject together!

**Comment by athal7** [comment]
Agreed, closing. 

Re the multiple node question, the full umbrella is running in a single docker container, and that container is replicated horizontally via kubernetes. I had gone with the separation previously, but agreed with what you were posting about that not being an umbrella app.

Thanks again!

**Pull request closed without merging**
